### ISSUE TITLE
[Feature request] Option to specify the number of forecast items

### ISSUE THREAD

**Issue by kaizersoje** [Yevgenium/weather-chart-card#105]
Is it possible to specify the number of forecast items similar to the [weather-card](https://github.com/bramkragten/weather-card)?

```yaml
type: custom:weather-card
entity: weather.yourweatherentity
forecast: true
hourly_forecast: false
number_of_forecasts: 5
```
