### ISSUE TITLE
card empty, "please, check your weather entity"

### ISSUE THREAD

**Issue by elektrinis** [Yevgenium/weather-chart-card#142]
Probably not a bug, not sure where the issue is, maybe someone will help to sort this out.
I have two cards and they became empty on all devices (few months ago), just getting messages to check my entity. 
![Screenshot_20240705-152121](https://github.com/Yevgenium/weather-chart-card/assets/15337792/0ba5203d-b175-473c-b96c-b972ccce1a52)

This screenshot is from android app, where one of cards suddenly appeared, other is still empty. On all other devices both cards only display the message. I have cleared browser cache and cookies, also ha app data on other mobile devices.

Here's my yaml:
```
  - type: custom:weather-chart-card
    entity: weather.home_hourly
    icon_style: style1
    forecast:
      style: style1
    show_time: true
    show_day: true
    show_date: true
    animated_icons: true
  - type: custom:weather-chart-card
    entity: weather.home
    icon_style: style1
    forecast:
      style: style1
    show_main: false
    show_attributes: false
```

I am using the stock Met.no integration for weather.

Any ideas?
