### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by fmonday** [Yevgenium/weather-chart-card#33]
Installation on MacOS Catalina 10.15.4, HA 0.109.1, Python 3.8.2 but also happened on 3.7.7. Card UTD per HACS, v0.2.6. 

```
lovelace:
  resources:
    - url: /hacsfiles/lovelace-weather-card-chart/weather-card-chart.js
      type: module
```

This is the best-looking weather card, great work. Recently however with no configuration changes, the y-axis (temperature) became intermittently impossible to read; it seems like it decided to add decimals and in the process the first digit was cropped. Also getting this error:
```
ERROR (MainThread) [frontend.js.latest.202004271] https://myurl.org/hacsfiles/lovelace-weather-card-chart/weather-card-chart.js:297:42 TypeError: undefined is not an object (evaluating 'this.weatherObj.attributes.forecast')
```
This happens with both openweathermap and darksky as the source. 

<img width="270" alt="Screen Shot 2020-04-30 at 7 00 00 PM" src="https://user-images.githubusercontent.com/43834799/80767115-2c2de200-8b15-11ea-96a9-966838706567.png">
