### ISSUE TITLE
hourly mode is detected but only shows temps

### ISSUE THREAD

**Issue by X1pheR** [Yevgenium/weather-chart-card#75]
Hour mode is detected but it only displays the temperature.. Could you include the other attributes also? Or at least configurable? Below is a screenshot and overview of how the default weather hourly output looks like.

![image](https://user-images.githubusercontent.com/569396/132375721-13f7362d-35df-4a01-938c-48065bea8184.png)

```
temperature: 24.5
humidity: 43
pressure: 1022.7
wind_bearing: 142.4
wind_speed: 6.8
attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute.
forecast: 
- condition: sunny
  precipitation: 0
  precipitation_probability: 0
  temperature: 24.2
  datetime: '2021-09-07T16:00:00+00:00'
  wind_bearing: 130.3
  wind_speed: 6.5
- condition: sunny
  precipitation: 0
  precipitation_probability: 0
  temperature: 23.9
  datetime: '2021-09-07T17:00:00+00:00'
  wind_bearing: 97
  wind_speed: 7.9
```
